### ISSUE TITLE
Feature: Homepage

### ISSUE THREAD

**Issue by LiamFenneman** [LiamFenneman/Personal-Website#6]
# Feature: Homepage

# Description

A complete homepage.

## Tasks (complete in order)
- [ ] [Task 1: Hero Section](#1 )
- [ ] [Task 2: Projects Section](#3 )
- [ ] [Task 3: About Section](#4 )
- [ ] [Task 4: Contact Section](#5 )
